# Generated by Django 2.2.13 on 2021-11-29 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='userProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('DONAR', 'DONAR'), ('RECEPTOR', 'RECEPTOR')], max_length=10, null=True)),
                ('first_name', models.CharField(max_length=500)),
                ('last_name', models.CharField(blank=True, max_length=500)),
                ('email', models.CharField(max_length=500)),
                ('phone_number', models.CharField(max_length=200, null=True)),
                ('dob', models.DateField(null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], max_length=250)),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile/%Y/%m/%d')),
                ('address', models.TextField(null=True)),
                ('otp', models.CharField(blank=True, max_length=250)),
                ('social_token', models.CharField(blank=True, max_length=500, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
