# Generated by Django 2.2.13 on 2021-11-29 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=500)),
                ('last_name', models.CharField(blank=True, max_length=500)),
                ('email', models.CharField(max_length=500)),
                ('phone_number', models.CharField(max_length=200, null=True)),
                ('dob', models.DateField(null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], max_length=250)),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile/%Y/%m/%d')),
                ('address', models.TextField(null=True)),
                ('otp', models.CharField(blank=True, max_length=250)),
                ('deposit_amount', models.IntegerField(blank=True, default=0, null=True)),
                ('withdraw_amount', models.IntegerField(blank=True, default=0, null=True)),
                ('currency', models.CharField(blank=True, max_length=250)),
                ('login_type', models.CharField(blank=True, max_length=250, null=True)),
                ('social_token', models.CharField(blank=True, max_length=500, null=True)),
                ('time_zone', models.CharField(blank=True, max_length=250)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='userProfile',
        ),
    ]
